### ISSUE TITLE
 --socket=session-bus is an overly broad permission

### ISSUE THREAD

**Issue by bbhtt** [flathub/com.github.naaando.lyrics#2]
https://github.com/flathub/com.github.naaando.lyrics/blob/c99889a4fdd2bfd70f5a2b28bcff3d69a704b115/com.github.naaando.lyrics.json#L12

This bypasses the sandbox offered by Flatpak.

Steps to resolve:

1. Remove --socket=session-bus
2. Run the application with --log-session-bus. This will print a log of which dbus calls are actually used and blocked.
3. Add specific --talk-name=org.example.Name to talk to a service. Occasionally you'll need to add --own-name=org.example.Name to own a name.

I haven't checked but I assume this is being used for MPRIS?

**Comment by hfiguiere** [comment]
see https://github.com/flathub/flathub/issues/2785
